### ISSUE TITLE
Add Nginx for Deployment section in README

### ISSUE THREAD

**Issue by peter279k** [odan/prisma#2]
As title, this Slim skeleton uses the Apache as HTTP server in the deployment section.
It should add another guide about using the Nginx as HTTP server in the deployment section.
If possible, I can do that. And I need  to know is where I can get started with this?

Thanks.

**Comment by odan** [comment]
Where do you found a Apache specific setup description in the documentation?

**Comment by peter279k** [comment]
Hi @odan, thank you for your reply.
I mention that because I found the `.htaccess` file on this repository and I don't find any setup description on this repo.
I mean we can add the deployment guides for this repo and let developers build easily.
I think we can provide the Nginx and Apache guides for building this repository. 

Thanks.

**Comment by odan** [comment]
If you like, you can add a new installation section here: 

https://github.com/odan/prisma/blob/master/docs/readme.md
